# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: j.lewis@digitaldimension.com.mx
author_name: Jason Wade Lewis
preset_name: starter
project_name: fullstackv2-demo-frontend

